// dev-apps/React/src/App.tsx
import { useState } from "react";
import "./App.css";
// import "web-comp/button/index.js";
// import "web-comp/input/index.js";
// TODO 如何去掉 index 'crossui-react/index' --> 'crossui-react'
import { Input } from "crossui-react/index";

function App() {
  const [inputValue, setInputValue] = useState("");
  const handleChange = (e) => {
    setInputValue(e.detail);
  };

  return (
    <>
      <div>
        <h1>Input 组件</h1>
        <label>web component 输入</label>
        <Input change={handleChange}></Input>
        <div>
          <label>显示：</label>
          {inputValue}
        </div>
      </div>
    </>
  );
}

export default App;

// dev-apps/Vue3/src/App.vue
<script setup lang="ts">
import Input from "crossui-vue3/input/index.vue";
import { ref } from "vue";
// import "web-comp/button/index.js";
// import "web-comp/input/index.js";
const inputValue = ref("");
function change(e) {
  console.log("input", e.detail);
  inputValue.value = e.detail;
}
</script>

<template>
  <!-- <c-button @click="cbtn" type="danger">
  </c-button> -->
  <h1>我是Vue3应用</h1>

  <h2>Input 组件</h2>
  <label>输入</label>
  <Input @change="change" />
  <div>显示：{{ inputValue }}</div>
</template>

<style scoped></style>
