// components/react/input/index.tsx
import React, { useEffect, useRef } from "react";
import useEvent from "../common/use-event";
import "@crossui/web-components/input/index.js";

export default function Input(props) {
  const inputRef = useRef();
  const unListen = useEvent(props, inputRef, ["change"]);
  useEffect(() => {
    return () => {
      unListen();
    };
  }, []);
  return <c-input ref={inputRef}></c-input>;
}

declare global {
  namespace JSX {
    interface IntrinsicElements {
      "c-input": any;
    }
  }
}

// components/vue3/input/index.vue
<template>
  <c-input @change="emit('change', $event)" :value="value"></c-input>
</template>

<script setup lang="ts">
import { ref } from "vue";
import "crossui-web-components/input";
const value = ref("");
const emit = defineEmits<{ (event: "change", e: CustomEvent): void }>();
</script>

<style lang="scss" scoped></style>
